on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Delete previous Discord message (if exists)
        run: |
          if [ -f last_message_id.txt ]; then
            last_id=$(cat last_message_id.txt)
            curl -X DELETE "https://discord.com/api/webhooks/1392613771431772290/CF8wOTc4C5PrAXuptJA7faryW-EbHtqSOVokByqX3hXwvf_cixyswTV5-Frp9MavhzVY/github/messages/$last_id"
          fi

      - name: Send new Discord message
        id: send_discord
        run: |
          response=$(curl -H "Content-Type: application/json" -X POST -d '{"content":"New commit!","username":"Dan Bot"}' "https://discord.com/api/webhooks/1392613771431772290/CF8wOTc4C5PrAXuptJA7faryW-EbHtqSOVokByqX3hXwvf_cixyswTV5-Frp9MavhzVY/github?wait=true")
          echo $response | jq -r '.id' > last_message_id.txt

      - name: Upload last message ID for next run
        uses: actions/upload-artifact@v4
        with:
          name: last_message_id
          path: last_message_id.txt

