on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Dan bot"
          avatar_url: "https://imgur.com/a/UeKhHWu"
          message: "Logs updated @ https://crtve.github.io/WvW-Logs/"
